Cylc to scheduler
cylc/cylc-doc pull request #172
Opened 2020-11-06 11:22 UTC by datamel

Small PR, will fix the doc build after https://github.com/cylc/cylc-flow/pull/3907 goes in.
Changes references from [cylc] to [scheduler].

2020-11-25 13:32 UTC, MetRonnie requested changes

2020-11-25 13:32 UTC, MetRonnie commented on cylc/doc/etc/tutorial/consolidation-tutorial/flow.cylc
> +[scheduler]uler]
Oops 😄

2020-11-25 13:34 UTC, datamel commented on cylc/doc/etc/tutorial/consolidation-tutorial/flow.cylc
> +[scheduler]uler]
Woops, no idea how I missed these :)

2020-11-25 15:03 UTC, MetRonnie commented
Test failure is due to using old version of `actions/setup-node`, #174 should fix it

2020-11-25 15:29 UTC, MetRonnie requested changes

2020-11-25 15:29 UTC, MetRonnie commented on cylc/doc/etc/tutorial/consolidation-tutorial/flow.cylc
> +[scheduler]]
Still not quite right

2020-12-03 12:15 UTC, wxtim commented on cylc/doc/etc/tutorial/consolidation-tutorial/flow.cylc
> +[scheduler]]
```suggestion
[scheduler]
```

2020-12-03 12:37 UTC, datamel commented on cylc/doc/etc/tutorial/consolidation-tutorial/flow.cylc
> +[scheduler]]
yikes, not sure what is wrong with me!

2020-12-03 12:44 UTC, MetRonnie approved these changes

2020-12-03 13:56 UTC, wxtim approved these changes
✅

2020-12-03 13:58 UTC, MetRonnie commented
❔

2020-12-03 14:16 UTC, merged