document graph line continuation on boolean
cylc/cylc-doc pull request #296
Opened 2021-09-10 12:01 UTC by wxtim

Document https://github.com/cylc/cylc-flow/issues/4342

2021-09-10 17:37 UTC, kinow approved these changes

2021-09-21 07:57 UTC, hjoliver approved these changes

2021-09-21 07:58 UTC, hjoliver requested changes

2021-09-21 07:58 UTC, hjoliver commented on src/user-guide/writing-workflows/scheduling.rst
> +dependency arrows (``=>``), booleans (``&``, ``|``),
```suggestion
dependency arrows (``=>``), boolean operators (``&``, ``|``),
```

2021-09-21 07:58 UTC, hjoliver commented on src/workflow-design-guide/style-guide.rst
> +trigger arrows and booleans imply line continuation:
```suggestion
trigger arrows and boolean operators imply line continuation:
```

2021-09-24 07:03 UTC, merged

2021-09-24 07:03 UTC, wxtim commented
Merged because Kinow had approved + I made the changes @hjoliver  asked for + it's documentation not functional code.