companion to https://github.com/cylc/cylc-flow/pull/4521
cylc/cylc-doc pull request #320
Opened 2021-11-17 13:17 UTC by wxtim

2021-11-17 20:48 UTC, hjoliver requested changes
:+1: just a couple of suggestions to make the text more concise.

2021-11-17 20:48 UTC, hjoliver commented on src/user-guide/running-workflows/running-workflows.rst
> +Files created at workflow start
```suggestion
Files Created at Workflow Start
```

2021-11-17 20:48 UTC, hjoliver commented on src/user-guide/running-workflows/running-workflows.rst
> +is recorded, with all templating expanded:
```suggestion
At startup a folder ``log/flow-config`` is created to record the workflow configuration,
with all templating expanded:
```

2021-11-17 20:48 UTC, hjoliver commented on src/user-guide/running-workflows/running-workflows.rst
> +  will not be merged.
```suggestion
- ``flow-processed.cylc`` - the current workflow configuration
  with templating expanded, and duplicate sections unmerged.
```

2021-11-17 20:48 UTC, hjoliver commented on src/user-guide/running-workflows/running-workflows.rst
> +  Duplicate sections will be merged.
```suggestion
- ``<datetime-stamp>-<start/restart/reload>`` - the config at each time the workflow
 was started, restarted, or reloaded; with duplicate sections merged.
```

2021-11-17 20:48 UTC, hjoliver commented on src/user-guide/running-workflows/running-workflows.rst
> +   in these files.
```suggestion
   Look at these files to see the result of templating in the workflow config.
```

2021-11-18 09:50 UTC, datamel approved these changes
I'm happy with the changes as suggested by @hjoliver.
I have built the docs and read through the changes.
Thanks @wxtim. Approving under the assumption that changes requested will be implemented.

2021-11-22 02:09 UTC, hjoliver approved these changes

2021-11-22 02:10 UTC, merged

2021-11-22 09:34 UTC, wxtim commented
@hjoliver  I'm a little confused as to why you merged the doc pr before the associated change...

2021-11-22 15:34 UTC, MetRonnie commented
I think we will have to temporarily revert this change as this is an rc1 change? And then revert the revert after the 8.0b3 docs have been deployed

2021-11-22 19:27 UTC, hjoliver commented
Oops, sorry, bad :grimacing:

2021-11-22 19:37 UTC, hjoliver commented
I've reverted this merge on master.  @wxtim has deleted this PR branch, but I've recovered the commits and will push to my fork to reopen.