Install rose in editable mode to avoid symlink issues
cylc/cylc-doc pull request #341
Opened 2021-11-24 14:56 UTC by wxtim

2021-11-24 16:07 UTC, oliver-sanders commented on .github/workflows/deploy.yml
> -            "metomi-rose[all] @ git+https://github.com/metomi/rose@${meto_rose}" \
Need to keep the meto_rose tag it is important for deployment.

2021-11-24 16:08 UTC, oliver-sanders commented on src/user-guide/running-workflows/running-workflows.rst
> +Files Created at Workflow Start
Intended?

2021-11-25 09:14 UTC, wxtim commented on src/user-guide/running-workflows/running-workflows.rst
> +Files Created at Workflow Start
No.

2021-11-25 10:50 UTC, wxtim commented on .github/workflows/deploy.yml
> +          pip install -e \
```suggestion
          pip install  \
```

2021-11-25 10:50 UTC, wxtim commented on .github/workflows/nightly.yml
> +          pip install -e \
```suggestion
          pip install  \
```

2021-11-25 10:50 UTC, wxtim commented on .github/workflows/test_tutorial_workflow.yml
> +          pip install -e \
```suggestion
          pip install  \
```

2021-11-25 11:22 UTC, wxtim commented on .github/workflows/test.yml
> +          pip install \
```suggestion
          pip install  \
```

2021-11-25 11:23 UTC, wxtim commented on .github/workflows/test.yml
> +          pip install \
```suggestion
          pip install  \
```

2021-11-25 13:20 UTC, oliver-sanders requested changes

2021-11-25 13:20 UTC, oliver-sanders commented on .github/workflows/deploy.yml
> +          git clone --depth 1 https://github.com/metomi/rose ../rose
```suggestion
          git clone --depth 1 -b "${meto_rose}" https://github.com/metomi/rose ../rose
```

2021-11-25 13:20 UTC, oliver-sanders commented on .github/workflows/test.yml
> +          git clone --depth 1 https://github.com/metomi/rose ../rose
```suggestion
          git clone --depth 1 -b "${meto_rose}" https://github.com/metomi/rose ../rose
```

2021-11-25 13:20 UTC, oliver-sanders commented on .github/workflows/deploy.yml
> +          pip install -e ../rose
Need to pip install `[all]`.

2021-11-25 13:20 UTC, oliver-sanders commented on .github/workflows/test.yml
> +          pip install -e ../rose
Need to pip install `[all]`.

2021-11-25 13:20 UTC, oliver-sanders commented on .github/workflows/test_tutorial_workflow.yml
> +          pip install -e ../rose
Note: **don't** need to pip install `[all]` here.

2021-11-25 13:20 UTC, oliver-sanders commented on .github/workflows/test_tutorial_workflow.yml
> +          git clone --depth 1 https://github.com/metomi/rose ../rose
```suggestion
          git clone --depth 1 -b "${meto_rose}" https://github.com/metomi/rose ../rose
```

2021-11-25 13:20 UTC, oliver-sanders commented on .github/workflows/nightly.yml
> +          pip install -e ../rose
Need to pip install `[all]`.

2021-11-25 13:35 UTC, oliver-sanders commented on .github/workflows/test_tutorial_workflow.yml
> +          pip install -e ../rose[all]
```suggestion
          pip install -e ../rose
```

2021-11-25 13:35 UTC, oliver-sanders commented on .github/workflows/test_tutorial_workflow.yml
> +          pip install -e ../rose[all]
https://github.com/cylc/cylc-doc/pull/341#discussion_r756883323

2021-11-25 14:39 UTC, wxtim commented on .github/workflows/test_tutorial_workflow.yml
> +          meto_rose: ${{ github.event.inputs.metomi-rose-tag || 'master' }}
```suggestion
```

2021-11-25 14:39 UTC, wxtim commented on .github/workflows/test_tutorial_workflow.yml
> +          git clone --depth 1 --branch "${meto_rose}" https://github.com/metomi/rose ../rose
```suggestion
          git clone --depth 1 --branch "${rose_ref}" https://github.com/metomi/rose ../rose
```

2021-11-25 14:40 UTC, oliver-sanders approved these changes

2021-11-25 14:49 UTC, merged