Document Cylc 728
cylc/cylc-doc pull request #480
Opened 2022-06-16 13:52 UTC by wxtim

Will only work with branch from https://github.com/cylc/cylc-flow/pull/4900

**Requirements check-list**
- [x] I have read `CONTRIBUTING.md` and added my name as a Code Contributor.

2022-06-27 18:09 UTC, MetRonnie requested changes
728 -> lint

2022-07-22 10:07 UTC, datamel approved these changes
Minor comment, you know our users level of knowledge better than me so I'll leave it up to you.

2022-07-22 10:25 UTC, wxtim commented on src/7-to-8/major-changes/config-changes.rst
> +Because some workflows use includes which may not be switched on at
Agreed!

2022-07-22 10:26 UTC, wxtim commented on src/7-to-8/major-changes/config-changes.rst
> +Because some workflows use includes which may not be switched on at
```suggestion
Because some workflows use include directives (which may be switched off by Jinja2 or
Empy) at
```

2022-07-22 10:56 UTC, MetRonnie commented on src/7-to-8/major-changes/config-changes.rst
> +Because some workflows use includes which may not be switched on at
```suggestion
Because some workflows use ``if...else`` branches which may not be switched on at
```

2022-07-27 12:48 UTC, MetRonnie approved these changes
1 suggestion

2022-07-27 12:48 UTC, MetRonnie commented on src/7-to-8/major-changes/config-changes.rst
> +Because some workflows use ``if...else`` branches which may not be switched on at
```suggestion
Because some workflows use Jinja2 or EmPy branches which may not be switched on at
```

2022-07-27 12:57 UTC, merged