Fix tutorial example
cylc/cylc-doc pull request #540
Opened 2022-09-22 10:41 UTC by oliver-sanders

See https://github.com/cylc/cylc-flow/issues/5150

**Requirements check-list**
- [x] I have read `CONTRIBUTING.md` and added my name as a Code Contributor.

2022-09-22 10:42 UTC, oliver-sanders commented on src/tutorial/scheduling/datetime-cycling.rst
> -.. csv-table::
These tables weren't working well (horizontal scrollbar and recurrences split over two lines), switched to a regular definition list.

2022-09-22 10:43 UTC, oliver-sanders commented on src/tutorial/scheduling/datetime-cycling.rst
> -   ``+PT1H/T00``, "every day starting on the first midnight after the point one
This was the broken recurrence.

2022-09-27 13:59 UTC, datamel approved these changes
This looks good to me, thanks. 

Quick separate query which I noticed after building this (although is unrelated to this pr). When you build the docs do you get the images rendering incorrectly?...
![image](https://user-images.githubusercontent.com/37735232/192546890-2f4f7bf2-643e-4266-a9f3-f57b0bd4afd6.png)
If this isn't just a Mel problem I can pop an issue up for it.

2022-09-27 14:32 UTC, oliver-sanders commented
That looks like this issue - https://github.com/cylc/cylc-doc/pull/246

We worked around it by using a different version of Graphviz in the deployment actions but I don't think we have have a proper fix.

2022-09-28 12:25 UTC, MetRonnie requested changes

2022-09-28 12:25 UTC, MetRonnie commented on src/tutorial/scheduling/datetime-cycling.rst
> +   after the 1st of January at 12:00 (i.e. ``2000-01-02T00``).
These are broken too?

2022-09-30 01:28 UTC, hjoliver commented
Spellcheck error fixed by #543

2022-09-30 01:28 UTC, merged