tui: document recent enhancements
cylc/cylc-doc pull request #663
Opened 2023-10-12 10:07 UTC by oliver-sanders

Documents #5731

**Requirements check-list**
- [x] I have read `CONTRIBUTING.md` and added my name as a Code Contributor.

2023-12-19 14:57 UTC, oliver-sanders commented on src/reference/changes.rst
There is a changelog file in each repository.

Additionally, we document major user-facing changes here. We tend to write a Discourse post about each of the features outlined here once the version has been released to help raise awareness of the new features.

2023-12-20 13:16 UTC, markgrahamdawson requested changes
I've built it locally and looks good

2023-12-20 14:23 UTC, oliver-sanders commented on src/7-to-8/major-changes/ui.rst
> +It can by used to monitor and control any workflows running under your user
```suggestion
It can be used to monitor and control any workflows running under your user
```

2023-12-20 14:25 UTC, markgrahamdawson approved these changes

2023-12-20 14:30 UTC, merged