document graph branching with multiple optional outputs
cylc/cylc-doc pull request #772
Opened 2024-11-07 15:07 UTC by oliver-sanders

A topic which periodically comes up but is not presently documented.

See also: https://github.com/cylc/cylc-flow/issues/5729

**Requirements check-list**
- [x] I have read `CONTRIBUTING.md` and added my name as a Code Contributor.

2024-11-07 22:14 UTC, hjoliver requested changes
Two minor typos.

Personal preference that I'm not super-invested in, but see what you think:

```
one:fail? & two:fail? => run_if_both_fail
```
I suppose this reduces verbosity by conveying additional information in the task name,  but there's a risk that new users might think the name is magic (i.e., functional in some way) or is something other than a simple task name (it's a weird task name after all).  IMO this would be better:

```
one:fail? & two:fail? => three  # run three if both one and two fail
```

2024-11-07 22:14 UTC, hjoliver commented on src/user-guide/writing-workflows/scheduling.rst
> +To prevent the workflow from stalling in the third case, it is necessay to use
```suggestion
To prevent the workflow from stalling in the third case, it is necessary to use
```

2024-11-07 22:14 UTC, hjoliver commented on src/user-guide/writing-workflows/scheduling.rst
> +combination of success/failre for the two tasks:
```suggestion
combination of success/failure for the two tasks:
```

2024-11-08 09:50 UTC, wxtim approved these changes
Good. Please fix the spelling errors Hilary spotted.

2024-11-08 10:07 UTC, oliver-sanders commented
> Two minor typos.
>
> Personal preference that I'm not super-invested in, but see what you think:

Usually these review comments go the other way, preferring concrete to abstract names.

Especially given the context, I don't think people will think these names are "magic", e.g. there's "recover" task in the previous example and an "ugly" task in the next one.

2024-11-08 10:27 UTC, hjoliver commented
Well, "recover" conveys what the task does (/what its purpose is), which kinda makes it a normal task name. And abstract task names are fine when their purpose doesn't matter for the sake of example. 

"run_if_both_fail" is different, and redundant actually, because it spells out its own triggering condition which is already evident in the graph. 

Plus the other task names in the example are abstract and sensibly related to "three".

2024-11-08 10:35 UTC, oliver-sanders commented
(will leave you two to battle that out)

2024-11-08 11:19 UTC, hjoliver commented
(but @wxtim hasn't given an argument one way or the other on this .. it seems you and I have to decide!)

2024-11-08 11:37 UTC, wxtim commented
In my opinion none of us can decide who is right on this because we are too close to the problem and we should either accept it or go and test it on a user.

2024-11-08 19:24 UTC, hjoliver commented
I rather like that description (running mental models of users in our heads)!  ... but asking a real user, or even a bunch of them, would not really be sufficient. There are many different kinds of user, and we can't run surveys for every little detail of this nature. So unfortunately we have to rely on our mental models for most of this stuff.

The task name `run_if_both_fail` is potentially confusing because it restates its own triggering condition. That is a strange way to name a task. Some readers may find that puzzling and may even wonder if it has some kind of functional meaning. And there's no real value in it because the information in the name is redundant - it's in the graph trigger already! 

The only counter-argument has been (paraphrasing) "I don't think it's confusing". 

A generic task name, with a description of the triggering in the text if we like, has zero confusion potential. We should always go with zero potential for confusion, right? 

Generic task names are good *when it doesn't matter what the task does in the context of the example*. They require no mental effort from the user. (Plus the other tasks in the same example are already generic!)

2024-11-08 19:29 UTC, hjoliver commented
@wxtim - I see @oliver-sanders has removed his assignment from the PR, despite being the author!

I presume that reflects his dislike for terminology discussions and similar, and doesn't care one way or the other.
(which is fair enough).

I do care one way or the other, and have given (IMO) good reasons for my stance.

 Do you have a good counter-argument?  If not, I'll push a change up...

If not, I guess I'll just push a change the branch...

2024-11-10 20:01 UTC, hjoliver approved these changes

2024-11-10 20:01 UTC, merged